### PR TITLE
improve positioning

### PR DESCRIPTION
**Pull request by jkroso**
it still isn't always correct but it is at least while the target isn't mostly off the screen. Oh I also added some positions. "left-top", "left-bottom" etc..

### CODE REVIEW

**Comment by jkroso** [comment]
snip20150524_3

This is the kind of problem this patch fixes. I've added a step where it goes OK its hanging over the edge so lets see if its better once shifting to "bottom-left" or "bottom-right" and picks the best fit

**Comment by jkroso** [comment]
A full blown logic programming solution would be ideal but this is good enough for my use case

**Comment by blowery** [comment]
@TooTallNate @retrofox any thoughts on this? would help us fix https://github.com/Automattic/wp-calypso/issues/2725

**Comment by TooTallNate** [comment]
@jkroso Thanks for the update! We've merged this along with some other changes in #56 :beers:.

**Pull request closed without merging**
